### ISSUE TITLE
Activity Controller example fails to dismiss activityViewController on iPad

### ISSUE THREAD

**Issue by seeker12** [erica/iOS-6-Cookbook#1]
The example app, Activity Controller, Chapter 8 / example 10, demonstrates a "roll your own activity", presenting a UIActivityViewController passing a UIActivity subclass instance, MyActivity, in the applicationActivities array. The MyActivity instance returns a TextViewController instance from its activityViewController method.

The presentation of the custom activityViewController and handling of the activityItems data works as described, however, though the -(void)done method handler is called by the TextViewController Done button event, in the iPad simulator and on an iPad device, the custom activityViewController (TextViewController) is not dismissed.

Per Apple UIActivity Class Reference documenting activityViewController:
"Discussion
The default implementation of this method returns nil. Subclasses that provide additional UI using a view controller can override this method to return that view controller. If this method returns a valid object, the system presents the returned view controller for you, instead of calling the performActivity method. On iPad, your view controller is presented inside of a popover. On iPhone and iPod touch, your view controller is presented modally.

Your custom view controller should provide a view with your custom UI and should handle any user interactions inside those views. Upon completing the activity, do not dismiss the view controller yourself. Instead, call the activityDidFinish: method and let the system dismiss it for you.

Note: If the view controller returned by this method presents additional view controllers, you are responsible for presenting and dismissing those view controllers. However, you must not dismiss the view controller returned by this method."
1. The custom activityViewController is presented in full screen modal view, rather than in a popover as the docs describe, and,
2. The activityViewController is not dismissed when the UIActivity activityDidFinish: method is called.

Is this an Apple bug? Or is there something I'm not doing correctly?

Thanks for the awesome book and recipes!

**Comment by erica** [comment]
This is discussed in-text.   "Adding a way for your activity to complete is important, especially when your controller doesn't have a natural endpoint. When your action uploads data to an FTP server, you know when it completes. If it Tweets, you know when the status posts. In this example, it's up to the user to determine when this activity finishes. Make sure your view controller contains a weak property pointing back to the activity, so you can send the did-finish method after your work concludes."

-- E

**Comment by erica** [comment]
Apparently this is a known issue for the iPad. Radars 12545554 / 12545600. Workarounds (e.g. adding completion handler to activity controller)  do not seem to work at this time. I'll keep watching this to see if anything resolves.

**Comment by ostapHorbach** [comment]
Did you find solution to this issue?
