### ISSUE TITLE
Recipe 10.7 Adding Action Drawers to Table - Delete button shown on drawer after swipe

### ISSUE THREAD

**Issue by ghost** [erica/iOS-6-Cookbook#2]
![2013-01-24 21 19 21](https://f.cloud.github.com/assets/3003461/96192/45a9e0f4-6696-11e2-9adb-577ea5cd4958.png)
Core iOS6 Developer's Cookbook pg 392. Downloaded the latest code from github. When you select a cell the drawer appears. However, if you perform a swipe gesture on the action drawer as if you wanted to delete the drawer you see the delete button in the drawer cell. If you select the delete button the code crashes in libobjc.A.dylib with 'objc_exception_throw' on the com.apple.main-thread (serial).

How can the code be modified to prevent the appearance of the delete button in the action cell? I'd like to still allow the swipe gestures.

**Comment by erica** [comment]
I just tested my code -- and it's not producing the behavior you're describing. As far as I can tell, there's no swiping enabled.

I tested on device as well as in the simulator.

-- E

**Comment by ghost** [comment]
Erica,
I've got a canEditRowAtIndexPath: that was allowing edits. This and other tableView methods will need to be implemented in a way that handles the drawer cell. When I return NO for all cells I get the behavior you are describing - no swiping enabled. I'll leave it that way for now while I figure out the changes needed and do some testing.

**Comment by ghost** [comment]
Erica,
Perhaps one simple way to do this is to allow edits and moves only if a drawer cell is not displayed. In which case returning !(self.actionRowPath) from canMoveRowAtIndexPath: and canEditRowAtIndexPath: may be all that is needed.
