### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by aehlke** [erica/iOS-6-Cookbook#5]
Thanks for this project! Should it be updated to iOS 7?

**Comment by erica** [comment]
iOS 7 cookbook is almost done. Rich Wardwell is helping out. — E

**Comment by aehlke** [comment]
Awesome! Thanks. Is there some space I can watch for it?

**Comment by Kozlov-V** [comment]
+1

**Comment by erica** [comment]
http://www.informit.com/store/core-ios-developers-cookbook-9780321948106

-- E

**Comment by Kozlov-V** [comment]
Thank you, I have to wait Mart 19, 2014 ((((
